/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-north-1",
  // aws_cognito_identity_pool_id: "ap-southeast-2:8769a63c-940d-4ee3-b838-fae7f229678f",
  // aws_cognito_region: "ap-southeast-2",
  aws_user_pools_id: "eu-north-1_JkrcuYENQ",
  aws_user_pools_web_client_id: "4la46vtomi2vof177o6ccds5e2",
  // oauth: {},
  // aws_appsync_graphqlEndpoint:
  //   "https://5ec7bh3mqrddpihjxougr34ioq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
  // aws_appsync_region: "ap-southeast-2",
  // aws_appsync_authenticationType: "API_KEY",
  // aws_appsync_apiKey: "da2-gfouhbqitvcbfm5htnhvyoyyja",
  // aws_user_files_s3_bucket: "redditclonea4f35ee94c414237ada7a8e3f084e8ed154921-dev",
  // aws_user_files_s3_bucket_region: "ap-southeast-2",
};

// AWS_COGNITO_USER_POOL_ID = "eu-north-1_JkrcuYENQ";
// AWS_COGNITO_CLIENT_ID = "4la46vtomi2vof177o6ccds5e2";
export default awsmobile;
